kind: pipeline
name: default

steps:
- name: build on pypi
  image: python:3.7.3-alpine3.9
  failure: ignore
  environment:
    PYPI_PW:
      from_secret: pypi-pw
  commands:
  - python3 setup.py sdist bdist_wheel
  - pip install twine
  - python3 -m twine upload -u Gabisonfire -p "$PYPI_PW" dist/*

- name: push to Github
  image: alpine/git
  depends_on:
  - build on pypi
  environment:
    SSH_KEY:
      from_secret: gab-key
    EMAIL:
      from_secret: email
  commands:
  - mkdir ~/.ssh
  - ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
  - echo "$SSH_KEY" > ~/.ssh/id_rsa
  - chmod 400 ~/.ssh/id_rsa
  - git clone git@github.com:Gabisonfire/justlog.git /tmp/justlog
  - apk add rsync
  - rsync -av --exclude=.git . /tmp/justlog
  - ls -la /tmp/justlog
  - git config --global user.email "$EMAIL"
  - git config --global user.name "Gabisonfire"
  - cd /tmp/justlog
  - git add -A .
  - git commit -am "$DRONE_COMMIT_MESSAGE"
  - git push

- name: update doc
  image: alpine
  depends_on: 
  - push to Github
  environment:
    TOKEN:
      from_secret: rdd-token
  commands:
  - apk add curl
  - curl -X POST -d "branches=master" -d "token=$TOKEN" https://readthedocs.org/api/v2/webhook/justlog/88460/
